services:
   catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

   basketdb:
        container_name: basketdb        
        restart: always
        ports:
        - "6379:6379"

   discountdb:
        container_name: discountdb
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Password@1
          POSTGRES_DB: DiscountDb
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data 
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin"]
            interval: 10s
            timeout: 5s
            retries: 5

   orderdb:
        container_name: orderdb        
        restart: always
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Rahul1234567"
        ports:
          - "1433:1433"      
        healthcheck:
         test: ["CMD", "bash", "-c", "</dev/tcp/localhost/1433"]
         interval: 10s
         timeout: 10s
         retries: 3
  

   catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

   basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"      
      - "GrpcSettings__DiscountUrl=http://discount.api:8080"
    depends_on:
      - basketdb
    ports:
      - "8001:8080"
   discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"
#      - ASPNETCORE_URLS=http://*:9002          
    depends_on:
      discountdb:
        condition: service_healthy
    ports:
      - "8002:8080"

   ordering.api:
     container_name: ordering.api
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Rahul1234567;TrustServerCertificate=true;"         
     depends_on:
      - orderdb      
     ports:
      - "8003:8080"   

   Portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

   pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
   
    

    
